### ISSUE TITLE
Books: clean aleph numbers

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-migrator-kit#15] opened 2018-10-17 13:37 UTC
More or less 25,000 records need to be corrected. 
One way to see if the value is an Aleph number is that the number stats with 000s:
https://cds.cern.ch/search?ln=en&sc=1&p=962__b%3A%22000*%22+or+785%3A%22000*%22+or+770%3A%22000*%22+or+780%3A%22000*%22+or+787%3A%22000*%22+or+772%3A%22000*%22&action_search=Search&op1=a&m1=a&p1=&f1=&c=Articles+%26+Preprints&c=Books+%26+Proceedings&c=Presentations+%26+Talks&c=Periodicals+%26+Progress+Reports&c=Multimedia+%26+Outreach

(The search is maybe not 100% accurate).

The fields that need to be checked are:
- [x] 962b
- [x] 770w
- [x] 772w
- [x] 780w
- [x] 785w
- [x] 787w

Additionally:
- [x] 035$$9CERCER

The matching needs to be done against 970__a where there is ‘CER’ and one needs to replace this value with the corresponding CDS record number. 

Here is an example:
https://cds.cern.ch/record/1163043?ln=en

As far as as know, there is also the field 035 that contains Aleph Numbers when $$9CERCER:  
Ex: https://cds.cern.ch/record/1220684?ln=en  -> to be checked if it is still in use for something

( requires #21 )

**Comment by ludmilamarian** [comment] 2019-02-07 16:08
@agentilb http://cds.cern.ch/record/611669/export/hm?ln=en contains 035$$CERCER but the number does not start with `000` is this correct? What should we do in this cases? Is this a valid Aleph number?

**Comment by agentilb** [comment] 2019-02-07 16:14
Hi, The 970 contains the Aleph number: 000611669 970__ $$a002371072CER, here it seems to match with 035a. So we can ignore this field.

**Comment by ludmilamarian** [comment] 2019-02-08 10:08
Hi @agentilb Unfortunately there is a bit of a grey zone. There are currently 13 records out of the ones we plan to migrate (71 records in total in CDS: see ticket) that have a 035 CERCER number that does not match the 970. Can you take a look and let me know how should I proceed with them?

Record: http://cds.cern.ch/record/688975        035$$9CERCER$$a2335634  970$$a002415211CER
Record: http://cds.cern.ch/record/108000        035$$9CERCER$$a2197315  970$$a000012716CER
Record: http://cds.cern.ch/record/644681        035$$9CERCER$$a0001170  970$$a002400422CER
Record: http://cds.cern.ch/record/960228        035$$9CERCER$$a0017737  970$$a002626513CER
Record: http://cds.cern.ch/record/395229        035$$9CERCER$$a0321541  970$$a002807641CER
Record: http://cds.cern.ch/record/682026        035$$9CERCER$$a0246139  970$$a002408512CER
Record: http://cds.cern.ch/record/887495        035$$9CERCER$$a0004029  970$$a002560162CER
Record: http://cds.cern.ch/record/1354483       035$$9CERCER$$a0321541  970$$a002807641CER
Record: http://cds.cern.ch/record/684955        035$$9CERCER$$a0013374  970$$a002411355CER
Record: http://cds.cern.ch/record/407879        035$$9CERCER$$a0334702  NO 970
Record: http://cds.cern.ch/record/277434        035$$9CERCER$$a0268334  970$$a000197258CER
Record: http://cds.cern.ch/record/277439        035$$9CERCER$$a0268012  970$$a000197263CER
Record: http://cds.cern.ch/record/278090        035$$9CERCER$$a0267712  970$$a000197947CER

**Comment by ludmilamarian** [comment] 2019-02-08 14:17
**787__w**
-> currently 107 records containing values in `787__w`: 
[cds_records_with_787w.txt](https://github.com/CERNDocumentServer/cds-migrator-kit/files/2845424/cds_records_with_787w.txt)
-> from the list it looks like a mix of CDS IDs and Aleph IDs; after checking the list, the rule that the Aleph number starts with `00` seems correct, so only these will be updated.

**Comment by agentilb** [comment] 2019-02-08 15:52
@ludmilamarian regarding those 13 records and the 58 mentioned in #21. I have checked a bit, and in some cases, the records are merged records or cloned records, that's explains the discrepancy between 035 and 970. 
But I guess, we should find if the values in 035 correspond to any 962/775/780/785/787, and check them manually to make sure there is no mismatch, otherwise, those fields can be ignored. 
WDYT?

**Comment by ludmilamarian** [comment] 2019-02-11 16:22
**770__w**
-> currently 16 records containing values in `770__w`:
[records_to_update_770.txt](https://github.com/CERNDocumentServer/cds-migrator-kit/files/2851965/records_to_update_770.txt)
 -> all are Aleph IDs

Out of these 16 records, 1 has a strange Aleph, and needs to be fixed manually:
- [ ] 229425 ['000223435 : 000144270']

**Comment by agentilb** [comment] 2019-02-12 09:31
@ludmilamarian 
For 229425, this is now corrected.
For 344633, this is an old record, that shouldn't be migrated: when 980:PERIDUMP, this is something similar to hidden records. Those need to be ignored during the migration (they are normally not searchable in CDS).

**Comment by ludmilamarian** [comment] 2019-02-13 09:46
**772__w**
-> 7 records: [cds_records_with_772w.txt](https://github.com/CERNDocumentServer/cds-migrator-kit/files/2859671/cds_records_with_772w.txt)

**Comment by ludmilamarian** [comment] 2019-02-13 12:43
**785__w**
-> 415 records

To fix manually @agentilb 

- [ ] 1283985 ['Continued by/Continued in part by/Split into/Absorbed by/Merged with', 'TITLE', '00SYST.NUMBER']
- [ ] 1286045 ['Continued by/Continued in part by/Split into/Absorbed by/Merged with', 'TITLE', '00SYST.NUMBER']
- [ ] 1336786 ['Continued by', 'Journal of the royal statistical society. series B (statistical methodology)', 'SYSNO']
- [ ] 1338587 ['split into', 'Sankhy\xc4\x81: The Indian Journal of Statistics, Series A and: Sankhy\xc4\x81: The Indian Journal of Statistics, Series B', 'SYSNO1 : SYSNO2']
- [ ] 1339672 ['Formed by the merger of', 'Sankhy\xc4\x81: The Indian Journal of Statistics, Series B', '002956689', 'Continued by', 'Sankhy\xc4\x81: The Indian Journal of Statistics', 'SYSNO']
- [ ] 1339675 ['Formed by the merger of', 'Sankhy\xc4\x81: The Indian Journal of Statistics, Series A', '002956689l', 'Continued by', 'Sankhy\xc4\x81: The Indian Journal of Statistics', 'SYSNO']
- [ ] 1339683 ['Split into', 'The Annals of Probability and: The Annals of Statistics', 'SYSNO1 : SYSNO2']

**Comment by ludmilamarian** [comment] 2019-02-13 14:53
**780__w**
-> 433 records  [cds_records_with_780w.txt](https://github.com/CERNDocumentServer/cds-migrator-kit/files/2860807/cds_records_with_780w.txt)

**Comment by ludmilamarian** [comment] 2019-02-13 16:48
**962__b**
-> ~194'000 records with a `962__b` value, thus we need to identify a mechanism to select the ones that refer to Aleph. @agentilb I need your help on this

* It looks like `962__l` sometimes keeps the provenance. The current possible values are `CER01', 'CERCER', 'ADMBUL', 'CER', 'MMD', 'PHOPHO'`  Can this information be used to know what needs to be updated? Can we assume that `CER01`, `CERCER` and `CER` are the same thing? Is the `ADMBUL` something that we can use? Looking at a few examples I could not find the correspondent ID in CDS

**Comment by agentilb** [comment] 2019-02-14 09:25
Hi @ludmilamarian 

In principle, only 962__b starting with 00 should be converted (at least for the articles, books, proceedings and standards). In most cases, indeed, there is a $$n with a conference code. In this case, it is actually a good idea to check against the 111__g of the corresponding record, if it is not too complicated. 

Then for the records that have 962__lCER or CERCER, it concerns mostly multimedia and archive records. In this case, I have the feeling that even if there is no 00 in 962__b the number is an Aleph number. The number of cases here is small, so I can check those myself. 

For the 962__l where the value is 'ADMBUL', 'MMD' or 'PHOPHO', it concerns mostly pictures. We have to check if there are Aleph number in there.

**Comment by ludmilamarian** [comment] 2019-02-14 09:41
@agentilb indeed the `962__l` is tricky. For example: https://cds.cern.ch/record/1299149/export/hm?ln=en has 962__lCER but the 962__b is a record ID, not an aleph number: https://cds.cern.ch/record/827684. I am sure I saw cases yesterday with 962__lCER but the `962__b` was not a record ID. In this case it will be difficult to treat them with a script. But I will let you investigate further, maybe you can discover a rule that we can apply. Meanwhile, I will focus on `962__b` that starts with `00`

**Comment by ludmilamarian** [comment] 2019-02-15 11:36
@agentilb records with `962__l`: [recs_with_962l.txt](https://github.com/CERNDocumentServer/cds-migrator-kit/files/2869083/recs_with_962l.txt)

**Comment by agentilb** [comment] 2019-02-18 13:08
Hi @ludmilamarian 

I have cleaned all the records with 962__l:'CER'. I.e. checking if the number was Aleph or CDS id, correcting when necessary, and deleting the 962__l. 
There is still one task pending with multi-record editor but by tomorrow, this will be cleaned for all Library and Archive records

962__l:PHOPHO-> it seems to correspond to records (mostly Bulletin articles) linked with photos. 
In this case, the corresponding record has a 035__ with $$9PHOPHO
Ex: https://cds.cern.ch/record/46124 linked to https://cds.cern.ch/record/43022?ln=en

962__l:MMD it seems to correspond to records (mostly Bulletin articles) linked with photos. 
In this case, the corresponding record has 970__a:'MMD' (and/or 035__9:'MMD')
Ex: https://cds.cern.ch/record/749053 linked to https://cds.cern.ch/record/615876

962__l:ADMBUL it seems to correspond to photo records linked with Bulletin issues (all are from the years 2000-2001). 
In this case, the corresponding record has 035:'ADMBUL' 
Ex: https://cds.cern.ch/record/41801 linked to https://cds.cern.ch/record/44476?ln=en

Those will be need to be modified at some point, but they are not part of the current migration.

**Comment by ludmilamarian** [comment] 2019-02-18 15:34
@agentilb Perfect, thank you! I created a new ticket #24 to have in mind for the photo migration.

**Comment by ludmilamarian** [comment] 2019-02-20 15:16
@agentilb `962__b` is a bit more tricky but we're getting there.
Out of 25'746 records to be fixed, 18'467 have a clear solution (searching for both aleph number and conference id gives only one result).
7'580 cases are not that straight forward, as the search for both aleph and conference gives either 0 or more than 1 result.
For these 7'580 I will search now only for aleph id, and if no results are found, search for conference id. Do you think this approach is ok? Would you like a more detail log for these 7'580? 
I will bibupload the 18'467 records that seem ok, and then work on figuring out the rest.

**Comment by agentilb** [comment] 2019-02-20 16:26
Hi @ludmilamarian 
18,5k records that have a clear solution is already a good thing! :-)
for the 7580 remaining records, there are maybe the cases of book chapters, that do not link to conference proceedings but to books, in this case, there is "book" in 962__n. Here, we can only rely on the Aleph number, and for sanity-check, verify that the corresponding record is a BOOK.
I believe this should work a for a large part of those records.

**Comment by ludmilamarian** [comment] 2019-02-20 16:30
@agentilb indeed, I discovered this case with `book` instead of conference id (I forgot to mention this!) and I only look for the aleph id in that case. I know that restricting to the book collection is going to help in this case - I have not yet done that

**Comment by ludmilamarian** [comment] 2019-02-22 15:10
@agentilb looking at the `book` cases, I see quite a lot of searches failing (no aleph ID). 
Investigating one case, I have discovered that in the past, some book updates were replacing fully the marcxml on CDS, erasing the 970/035. For example: https://cds.cern.ch/record/edit/compare_revisions?recid=214115&rev1=20130912172023&rev2=20130321051727
Trying to find a match for https://cds.cern.ch/record/857495. Do you have any pointers on how to address this issue. There could be the possibility of going back int he history for all the book records, but I would really keep this as the last option, as this will be super costly in terms of time/computation.

**Comment by agentilb** [comment] 2019-02-22 16:34
I fear this concerns  one specific collection of books which was curated by one student in 2013, unfortunately, I don't think we can easily retrieve the 970/035. But this should concern less than 200 records,  If I give you a selection of some 143 recids, is it easy to check the historical version before this Revision 2013-09-12 17:20:23 (I hope it was done in one time...) ?
https://cds.cern.ch/search?ln=en&cc=Books&sc=1&p=%22Landolt-Börnstein%22+and+964%3A%27*%27+and+916%3A201337&action_search=Search&op1=a&m1=a&p1=&f1=&c=Books&c=Book+Proposals&wl=0
The corresponding articles should be here I believe:
https://cds.cern.ch/search?ln=en&sc=1&p=LANDOLTBORNSTEIN1&action_search=Search&op1=a&m1=a&p1=&f1=&c=Articles+%26+Preprints&c=Books+%26+Proceedings&c=Presentations+%26+Talks&c=Periodicals+%26+Progress+Reports&c=Multimedia+%26+Outreach
And if you have a look to the 962, there are only 27 uniq Aleph number. 
So, my assumption if that we need to match those 27 Aleph numbers with the 143 books, I hope this should solve most of the cases you mention. Do you think this is feasible without being too costly? 
Or do you want me to have a look first to the logs of those errors, to see if the problem is wider than this specific collection?

**Comment by ludmilamarian** [comment] 2019-02-26 13:13
Hi @agentilb I fixed most of the linking, we are missing **1'895** links (so 1895 Aleph IDs still in 962__b) that have not been straightforward to fix. Out of these:
* **279 links have a conference code** -> in total 74 unique conference codes. Unfortunately, the exact search does not find these codes or finds two records for a conference code, so either there are typos or partial codes. Please take a look at the list bellow. Their associated Aleph IDs also are not findable. Some of them can be found linked to records that have been deleted, for example: https://cds.cern.ch/record/edit/?ln=en&#state=edit&recid=649525  At this point, I don't think there is anything I can do on my side, so I will leave the list with you to see if you can find a solution.
[aleph_linkinf_conference_codes.txt](https://github.com/CERNDocumentServer/cds-migrator-kit/files/2905561/aleph_linkinf_conference_codes.txt)

**Comment by agentilb** [comment] 2019-03-01 06:27
Hi @ludmilamarian, Thanks! I'll have a look to those lists, and let you know if something else can be done.

**Comment by ludmilamarian** [comment] 2019-03-11 10:35
@agentilb let me know how you wish to proceed, I would like to try to finish the task this week :-)

**Comment by agentilb** [comment] 2019-03-11 13:01
Hi @ludmilamarian, I started to study those lists manually with an intern, and I think we will be able to handle them on our side. This should be done by the end of the week. So no further action is required from you, I guess :-)

**Comment by ludmilamarian** [comment] 2019-03-11 13:17
That is fantastic news @agentilb ! This means we are close to have this project finished! I will leave the ticket open until you confirm that everything is fixed. Also, there are just a few cases left for `780__w`, some checkboxes from one of the previous comments.

**Comment by agentilb** [comment] 2019-03-11 13:26
@ludmilamarian the 780 are now done.

**Closed** 2019-04-03 07:51 UTC
Labels: books-sprint4, in progress

**Comment by agentilb** [comment] 2019-04-18 07:28
All Aleph numbers have now been cleaned in the 962__b.
